### ISSUE TITLE
Error with app.opitons.favicon[s]

### ISSUE THREAD

**Issue by lefteyecc-pu** [davewasmer/ember-cli-favicon#15]
It seems you have an error with the favicon options naming:

in index.js you have:

```
 this.options = app.options.favicons || {};
```

But specify to use the following in ember-cli-build.js:

```
var app = new EmberApp({
  favicon: {
  ...
```

Probably README instructions need to be updated?

**Comment by jlami** [comment]
And I actually needed to specify the following to fix the rootURL specified in environment:

```
module.exports = function(defaults) {
  var config = defaults.project.config(EmberApp.env());

  var app = new EmberApp(defaults, {
    favicons: {
        faviconsConfig: {
            path: config.rootURL,
        }
    },
```

So `faviconsConfig` is also different then the specified `config` key

**Comment by davewasmer** [comment]
I believe this is fixed - feel free to drop a note if not and I'll reopen.
