### ISSUE TITLE
Relative URLs should be generated

### ISSUE THREAD

**Issue by snifter** [davewasmer/ember-cli-favicon#17]
Version 1.0.0-beta.2 generates absolute URLs eg:
`<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">`

When in ember config baseUrl is set then favicons are not displayed because browser try to load icon from wrong directory. If url will be changed to relative:
`<link rel="apple-touch-icon" sizes="57x57" href="apple-touch-icon-57x57.png">`
then every thing will work fine.

**Comment by davewasmer** [comment]
This won't work nested routes, i.e. if you directly navigate to `example.com/some/nested/path`. Also, `baseUrl` has been deprecated (which is more a comment on how long I've left this issue unattended 😱).

Happy to address pathing issues if any still remain.
