### ISSUE TITLE
Excluding from fingerprint

### ISSUE THREAD

**Issue by AndersDJohnson** [davewasmer/ember-cli-favicon#5]
It'd be nice if there was an easy way to exclude favicon files from fingerprint.

Maybe we could expose an array of favicon file names as a property on the addon module, to be added by user to `fingerprint.exclude` in `ember-cli-build.js`? I've already requested this upstream in the `favicons` module - see https://github.com/haydenbleasel/favicons/pull/97.

For now, I'm doing that manually:

```
npm install --save-dev favicons
```

Then in `ember-cli-build.js`:

``` js
var _ = require('lodash');

var icons = require('favicons/config/icons.json');
var iconFiles = _(icons).map(function (icon) {
  return Object.keys(icon);
}).flatten().value();

var fingerprintExclude = [
  'favicon.png'
].concat(iconFiles);

module.exports = function (defaults) {
  var app = new EmberApp(defaults, {
    fingerprint: {
      enabled: true,
      exclude: fingerprintExclude,
      extensions: [
        'css',
        'gif',
        'jpg',
        'js',
        'png',
        'ico'
      ]
    }
  });
};
```

**Comment by davewasmer** [comment]
I believe the new 1.0.0-beta.x version should resolve this (it does all the work in the postProcess tree, so it should be missed by the fingerprinter). Let me know if that's not the case for you, and we can investigate explicitly excluding them.
