### ISSUE TITLE
HTML doesn't generate when cached

### ISSUE THREAD

**Issue by AndersDJohnson** [davewasmer/ember-cli-favicon#6]
HTML doesn't generate when cached. I think it's a bug upstream in `broccoli-favicon`, see my pull request to fix: https://github.com/davewasmer/broccoli-favicon/pull/2

**Comment by davewasmer** [comment]
The newly refactored v1.0.0-beta.2 uses an updated broccoli-favicon, which should resolve this. We can reopen if that's not the case.
