### ISSUE TITLE
Disabling platforms

### ISSUE THREAD

**Issue by lcpriest** [davewasmer/ember-cli-favicon#7]
In the README it implies the config is passed directly to the favicons module, does that mean we can use all of the same settings?
I have tried

```
    favicon: {
      icons: {
        firefox: false,
      },
      firefox: false,
      logging: true,
    },
```

But it didn't pass through. Admittedly, I'm using the ember-cli-build file and not a Brocfile, but I assumed that it didn't matter.

**Comment by baron1405** [comment]
Any update on this issue? I have tried a number of suggested workarounds but nothing worked. Is this plugin still active?

**Comment by davewasmer** [comment]
@lcpriest try with the new version, 1.0.0-beta.2.

Your config should look something like:

``` js
new EmberApp({
  favicons: {
    config: {
      // this object is passed straight through to the favicons module
      icons: { firefox: false }
    }
  }
});
```

**Comment by davewasmer** [comment]
Closing for now, but we can reopen if you are still having issues
