### ISSUE TITLE
Handle fingerprinting issue (or document)

### ISSUE THREAD

**Issue by elwayman02** [davewasmer/ember-cli-favicon#70]
As outlined in #62 & #66, this addon is wreaking havoc with people's deploys due to the favicon getting fingerprinted. It would be really nice if this addon handled the workaround by making sure the favicon did not get fingerprinted, or at least if the README documented the workaround so that we wouldn't spend a lot of time trying to figure out what we did wrong, only to maybe find the solution when digging through old issues in the project.

**Comment by davewasmer** [comment]
Fixed in the latest version.
