### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bgentry** [davewasmer/ember-cli-favicon#71]
The latest npm release of this addon still has this dependency:

```
"ember-cli-babel": "^5.1.6"
```

Which generates the following error:

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: myapp -> ember-cli-favicon -> ember-cli-babel
```

It seems this has been fixed on `master`. Can you please publish a new release?

**Comment by Alonski** [comment]
Any update on this?

**Comment by Exelord** [comment]
Released
