### ISSUE TITLE
Plans to remove PhantomJS dependency

### ISSUE THREAD

**Issue by patrickberkeley** [davewasmer/ember-cli-favicon#72]
This addon relies on: broccoli-favicon > favicons > svg2png. svg2png uses PhantomJS which[ has been sunsetted](https://github.com/ariya/phantomjs/issues/15344).

Are there any plans to remove the svg2png/PhantomJS dependency from this addon?

**Comment by davewasmer** [comment]
As your dependency graph illustrates, this addon is primarily just an Ember wrapper around `broccoli-favicon`, which in turn is a Broccoli wrapper around the `favicons` library, which I don't maintain. I'd suggest filing an issue on the [favicons repo](https://github.com/evilebottnawi/favicons/issues) to switch off `svg2png`, or filing an issue on the [svg2png repo](https://github.com/domenic/svg2png) to switch to using a different rendering platform.

There's not much I can do short of creating my own favicon generator to replace `favicons`, which is a bit beyond the scope I intended to tackle here :wink:.

**Comment by patrickberkeley** [comment]
Thanks for the info! I saw you maintain `broccoli-favicon`, so was thinking you might switch that off of `favicons`.

**Comment by davewasmer** [comment]
I'm open to that if it makes sense (i.e. if `favicons` has real problems, and there is an alternative that is a better solution). Despite the sunsetting, I haven't heard of any actual problems, nor any better alternatives.
