### ISSUE TITLE
Can we do this without coffeescript?

### ISSUE THREAD

**Issue by olleolleolle** [davewasmer/ember-cli-favicon#77]
Here's a dependency question: Would it be possible to get the functionality of `replace()` ([broccoli-replace](https://github.com/outatime/broccoli-replace)) without getting CoffeeScript as a dependency?

https://github.com/davewasmer/ember-cli-favicon/blob/db3dca86b43a13ae91f37ef8f62374c0a1b51865/index.js#L70-L78

**Comment by davewasmer** [comment]
Certainly - I'm sure there's likely another broccoli plugin out there that is better maintained and accomplishes a simpler task.

Also, should be pretty trivial to write our own based on `broccoli-filter`.

PR's welcome!
