### ISSUE TITLE
Plugin abandoned

### ISSUE THREAD

**Issue by baron1405** [davewasmer/ember-cli-favicon#8]
I am opening this issue to hopefully save others from spending time trying to get this plugin to work. The plugin and its dependency broccoli-favicon have not been updated to work with the latest versions of favicons, ember-cli, or the current broccoli plugin specification. Among other problems, this causes all possible icons to be generated regardless of any attempts at setting the favicons configuration. In addition the documentation and code appear to disagree as to whether the configuration key is "favicon" or "favicons". In any case, just create and reference favicons manually until this plugin is next updated.

**Comment by davewasmer** [comment]
The newly refactored v1.0.0-beta.1 should resolve the issues you mentioned. If it doesn't, please file specific bugs for any issues you come across.
